### ISSUE TITLE
why not mixin to the minecraft function that actually plays sound and just redirect it to the playcold version

### ISSUE THREAD

**Issue by walksanatora** [LudoCrypt/Sounds-So-Cold#2]
mixins are very powerfull and if you *really* wanted you could make it so that it applies to *all* sounds
if you want to be safe though you could have it apply to `Music` and `Ambien/Enviroment` (and un-classified)

**Comment by LudoCrypt** [comment]
You have no idea what you're talking about

**Comment by walksanatora** [comment]
i mean you could overwrite the
`playSound`  functions in `net.minecraft.world.level.Level`
then again i have not looked hard into how this mod works

**Comment by walksanatora** [comment]
(which i am now doing)

**Comment by walksanatora** [comment]
odd i cant seem to find 
`net/minecraft/client/sound/PositionedSoundInstance`

**Comment by walksanatora** [comment]
heck i cant even find `net/minecraft/client/sound`
unless is it a mapping diffrence

**Comment by walksanatora** [comment]
hmm
probally very hackily
why not just replace `SoundInstance` with `SoColdSoundInstance`

**Comment by walksanatora** [comment]
yeah thats more like what i mean
just replace the entirety of SoundInstace with SoColdSoundInstance
i think that is possible with mixins

**Comment by walksanatora** [comment]
ah wait SoundInstance is a interface

**Comment by walksanatora** [comment]
yeah my idea is to mixin `SoColdSoundInstance` directly into `AbstractSoundInstance` (or whatever the yarn-mapped version is)
thatway it is always pitch shifted
another idea would be to check which sound source it is

**Comment by LudoCrypt** [comment]
Nah
